export const categories = [
  "All",
  "Vegetables",
  "Fruit",
  "Dairy",
  "Grains",
  "Herbs",
] as const;

export const products = [
  {
    id: 1,
    name: "Organic Tomato Box",
    price: 12,
    category: "Vegetables",
    farm: "Green Valley Acres",
    location: "Bakersfield, CA",
    rating: 4.9,
    distance: "4 mi away",
    tag: "Best seller",
    accent: "#d9f39f",
    icon: "🍅",
    description: "Hand-picked, vine-ripened tomatoes from our regenerative farm.",
    stock: 22,
    organic: true,
  },
  {
    id: 2,
    name: "Citrus Harvest Basket",
    price: 18,
    category: "Fruit",
    farm: "Sunrise Orchard",
    location: "Fresno, CA",
    rating: 4.8,
    distance: "7 mi away",
    tag: "New this week",
    accent: "#ffe39c",
    icon: "🍊",
    description: "Sweet oranges and mandarins packed fresh from orchard rows.",
    stock: 15,
    organic: true,
  },
  {
    id: 3,
    name: "Farmhouse Milk",
    price: 8,
    category: "Dairy",
    farm: "Clover Creek Dairy",
    location: "Modesto, CA",
    rating: 4.7,
    distance: "11 mi away",
    tag: "Local favorite",
    accent: "#d0e9ff",
    icon: "🥛",
    description: "Pasture-raised milk collected early each morning.",
    stock: 31,
    organic: false,
  },
  {
    id: 4,
    name: "Heirloom Greens Mix",
    price: 15,
    category: "Vegetables",
    farm: "Meadow & Root",
    location: "Sacramento, CA",
    rating: 5.0,
    distance: "9 mi away",
    tag: "Fresh today",
    accent: "#cfe8c7",
    icon: "🥬",
    description: "A crisp mix of kale, spinach, and baby greens.",
    stock: 19,
    organic: true,
  },
  {
    id: 5,
    name: "Wildflower Honey",
    price: 14,
    category: "Herbs",
    farm: "Hillside Apiary",
    location: "Sonoma, CA",
    rating: 4.9,
    distance: "13 mi away",
    tag: "Small batch",
    accent: "#f7d8ae",
    icon: "🍯",
    description: "Raw, floral honey harvested from sustainable hives.",
    stock: 26,
    organic: true,
  },
  {
    id: 6,
    name: "Stoneground Flour Pack",
    price: 11,
    category: "Grains",
    farm: "Northwind Mill",
    location: "Ashland, OR",
    rating: 4.8,
    distance: "16 mi away",
    tag: "Baked fresh",
    accent: "#f9d3d3",
    icon: "🌾",
    description: "Slow-milled flour with a nutty flavor and local grain heritage.",
    stock: 12,
    organic: false,
  },
];

export const farms = [
  {
    name: "Green Valley Acres",
    subtitle: "Family farm",
    metric: "98% organic",
    city: "Bakersfield",
    reviews: 184,
    description: "Farming seasonal vegetables with regenerative soil practices.",
  },
  {
    name: "Sunrise Orchard",
    subtitle: "Fruit growers",
    metric: "12 varieties",
    city: "Fresno",
    reviews: 129,
    description: "Stone fruit and citrus grown with low-water irrigation systems.",
  },
  {
    name: "Clover Creek Dairy",
    subtitle: "Pasture raised",
    metric: "Daily pickup",
    city: "Modesto",
    reviews: 96,
    description: "Animal welfare-first dairy and yogurt from local pasture herds.",
  },
];

export const dashboardStats = [
  { label: "Weekly sales", value: "$8,420" },
  { label: "Orders", value: "132" },
  { label: "Active customers", value: "1,240" },
  { label: "Pickup rate", value: "94%" },
];

export const inventory = [
  { item: "Tomato Box", qty: 24, status: "In stock" },
  { item: "Greens Mix", qty: 18, status: "Low stock" },
  { item: "Milk", qty: 36, status: "In stock" },
  { item: "Wildflower Honey", qty: 12, status: "Low stock" },
];

export const recentOrders = [
  { id: "#1042", customer: "Alicia T.", item: "Tomato Box", total: "$24" },
  { id: "#1043", customer: "Mason P.", item: "Citrus Basket", total: "$31" },
  { id: "#1044", customer: "Daria L.", item: "Milk + Honey", total: "$22" },
  { id: "#1045", customer: "Noah B.", item: "Greens Mix", total: "$19" },
];
